// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgQP3O6pfbdj7UDyM1NaOQs8Jwj2r14uM',
    appId: '1:21008406923:web:01867f3a3de21034ddf78e',
    messagingSenderId: '21008406923',
    projectId: 'training-df528',
    authDomain: 'training-df528.firebaseapp.com',
    storageBucket: 'training-df528.appspot.com',
    measurementId: 'G-ZM4BV4LQP9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7A9OIwnrA0m7GscgPV6WjT4pEEUVYcz8',
    appId: '1:21008406923:android:fe67cef7fdaca0b8ddf78e',
    messagingSenderId: '21008406923',
    projectId: 'training-df528',
    storageBucket: 'training-df528.appspot.com',
  );
}
